import path from "node:path";
import ts from "typescript";
import { describe, expect, it } from "vitest";

/**
 * Guards the public API against accidental drift: the sorted export names of
 * `src/index.ts` must match the 6.0.4-alpha25 (last upstream release) list
 * exactly. Adding or removing an export is a breaking-change signal and must
 * be deliberate — update this list only when the API change is intended.
 */
const expectedExports = [
    "AllCellRenderers",
    "AutoGridColumn",
    "BaseDrawArgs",
    "BaseGridCell",
    "BaseGridColumn",
    "BaseGridMouseEventArgs",
    "BooleanCell",
    "BooleanEmpty",
    "BooleanIndeterminate",
    "BubbleCell",
    "CellActivatedEventArgs",
    "CellActivationBehavior",
    "CellArray",
    "CellBuffer",
    "CellClickedEventArgs",
    "CellList",
    "CellSet",
    "CompactSelection",
    "CompactSelectionRanges",
    "CopyBuffer",
    "CustomCell",
    "CustomRenderer",
    "DEFAULT_FILL_HANDLE",
    "DataEditor",
    "DataEditorCore",
    "DataEditorCoreProps",
    "DataEditorProps",
    "DataEditorRef",
    "DragHandler",
    "DrawArgs",
    "DrawCellCallback",
    "DrawHeaderCallback",
    "DrilldownCell",
    "DrilldownCellData",
    "EditListItem",
    "EditableGridCell",
    "EditableGridCellKind",
    "FillHandle",
    "FillHandleConfig",
    "FillHandleDirection",
    "FillPatternEventArgs",
    "GetCellsThunk",
    "GetRowThemeCallback",
    "GridCell",
    "GridCellKind",
    "GridColumn",
    "GridColumnIcon",
    "GridColumnMenuIcon",
    "GridDragEventArgs",
    "GridKeyEventArgs",
    "GridMouseCellEventArgs",
    "GridMouseEventArgs",
    "GridMouseGroupHeaderEventArgs",
    "GridMouseHeaderEventArgs",
    "GridMouseOutOfBoundsEventArgs",
    "GridSelection",
    "GroupHeaderClickedEventArgs",
    "HeaderClickedEventArgs",
    "HeaderIcon",
    "Highlight",
    "HoverEffectTheme",
    "ImageCell",
    "ImageEditorType",
    "ImageOverlayEditor",
    "ImageWindowLoader",
    "ImageWindowLoaderImpl",
    "InnerColumnExtension",
    "InnerGridCell",
    "InnerGridCellKind",
    "InnerGridColumn",
    "InternalCellRenderer",
    "Item",
    "KeyboardCellActivatedEvent",
    "LoadingCell",
    "MarkdownCell",
    "MarkdownDiv",
    "MarkdownDivProps",
    "MarkerCell",
    "NewRowCell",
    "NumberCell",
    "OutOfBoundsRegionAxis",
    "OverlayImageEditorProps",
    "PointerCellActivatedEvent",
    "PositionableMouseEventArgs",
    "PreventableEvent",
    "ProtectedCell",
    "ProvideEditorCallback",
    "ProvideEditorCallbackResult",
    "ProvideEditorComponent",
    "ReadWriteGridCell",
    "Rectangle",
    "RowGroup",
    "RowGroupingMapper",
    "RowGroupingMapperResult",
    "RowGroupingOptions",
    "RowIDCell",
    "SelectionBlending",
    "SelectionRange",
    "SizedGridColumn",
    "Slice",
    "Sprite",
    "SpriteMap",
    "SpriteProps",
    "TextCell",
    "TextCellEntry",
    "Theme",
    "UriCell",
    "UseRowGroupingResult",
    "ValidatedGridCell",
    "blend",
    "booleanCellIsEditable",
    "booleanCellRenderer",
    "bubbleCellRenderer",
    "decodeHTML",
    "default",
    "drawTextCell",
    "drilldownCellRenderer",
    "emptyGridSelection",
    "getCopyBufferContents",
    "getDefaultTheme",
    "getEmHeight",
    "getLuminance",
    "getMiddleCenterBias",
    "imageCellRenderer",
    "interpolateColors",
    "isEditableGridCell",
    "isInnerOnlyCell",
    "isObjectEditorCallbackResult",
    "isReadWriteCell",
    "isRectangleEqual",
    "isSizedGridColumn",
    "isTextEditableGridCell",
    "loadingCellRenderer",
    "markdownCellRenderer",
    "markerCellRenderer",
    "measureTextCached",
    "newRowCellRenderer",
    "numberCellRenderer",
    "parseToRgba",
    "protectedCellRenderer",
    "resolveCellsThunk",
    "roundedPoly",
    "roundedRect",
    "rowIDCellRenderer",
    "sprites",
    "textCellRenderer",
    "uriCellRenderer",
    "useColumnSizer",
    "useRowGrouping",
    "useTheme",
    "withAlpha",
];

function getExportedNames(entry: string): string[] {
    const program = ts.createProgram([entry], {
        allowJs: true,
        skipLibCheck: true,
        noEmit: true,
        module: ts.ModuleKind.ESNext,
        target: ts.ScriptTarget.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
    });
    const checker = program.getTypeChecker();
    const sourceFile = program.getSourceFile(entry);
    if (sourceFile === undefined) throw new Error(`Could not load ${entry}`);
    const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
    if (moduleSymbol === undefined) throw new Error(`No module symbol for ${entry}`);
    return checker
        .getExportsOfModule(moduleSymbol)
        .map(symbol => symbol.name)
        .sort();
}

describe("public API exports", () => {
    it("match the 6.0.4-alpha25 export list", () => {
        const entry = path.resolve("src/index.ts");
        expect(getExportedNames(entry)).toEqual(expectedExports);
    });
});
