import path from "node:path";
import ts from "typescript";
import { describe, expect, it } from "vitest";

/**
 * Guards the public API against accidental drift: the sorted export names of
 * `src/index.ts` must match the 6.0.4-alpha25 names plus the listed AI Fill
 * additions. Adding or removing an export is a breaking-change signal and must
 * be deliberate — update these lists only when the API change is intended.
 */

/** The 6.0.4-alpha25 (last upstream release) export names. */
const upstreamExports = [
    "AllCellRenderers",
    "AutoGridColumn",
    "BaseDrawArgs",
    "BaseGridCell",
    "BaseGridColumn",
    "BaseGridMouseEventArgs",
    "BooleanCell",
    "BooleanEmpty",
    "BooleanIndeterminate",
    "BubbleCell",
    "CellActivatedEventArgs",
    "CellActivationBehavior",
    "CellArray",
    "CellBuffer",
    "CellClickedEventArgs",
    "CellList",
    "CellSet",
    "CompactSelection",
    "CompactSelectionRanges",
    "CopyBuffer",
    "CustomCell",
    "CustomRenderer",
    "DEFAULT_FILL_HANDLE",
    "DataEditor",
    "DataEditorCore",
    "DataEditorCoreProps",
    "DataEditorProps",
    "DataEditorRef",
    "DragHandler",
    "DrawArgs",
    "DrawCellCallback",
    "DrawHeaderCallback",
    "DrilldownCell",
    "DrilldownCellData",
    "EditListItem",
    "EditableGridCell",
    "EditableGridCellKind",
    "FillHandle",
    "FillHandleConfig",
    "FillHandleDirection",
    "FillPatternEventArgs",
    "GetCellsThunk",
    "GetRowThemeCallback",
    "GridCell",
    "GridCellKind",
    "GridColumn",
    "GridColumnIcon",
    "GridColumnMenuIcon",
    "GridDragEventArgs",
    "GridKeyEventArgs",
    "GridMouseCellEventArgs",
    "GridMouseEventArgs",
    "GridMouseGroupHeaderEventArgs",
    "GridMouseHeaderEventArgs",
    "GridMouseOutOfBoundsEventArgs",
    "GridSelection",
    "GroupHeaderClickedEventArgs",
    "HeaderClickedEventArgs",
    "HeaderIcon",
    "Highlight",
    "HoverEffectTheme",
    "ImageCell",
    "ImageEditorType",
    "ImageOverlayEditor",
    "ImageWindowLoader",
    "ImageWindowLoaderImpl",
    "InnerColumnExtension",
    "InnerGridCell",
    "InnerGridCellKind",
    "InnerGridColumn",
    "InternalCellRenderer",
    "Item",
    "KeyboardCellActivatedEvent",
    "LoadingCell",
    "MarkdownCell",
    "MarkdownDiv",
    "MarkdownDivProps",
    "MarkerCell",
    "NewRowCell",
    "NumberCell",
    "OutOfBoundsRegionAxis",
    "OverlayImageEditorProps",
    "PointerCellActivatedEvent",
    "PositionableMouseEventArgs",
    "PreventableEvent",
    "ProtectedCell",
    "ProvideEditorCallback",
    "ProvideEditorCallbackResult",
    "ProvideEditorComponent",
    "ReadWriteGridCell",
    "Rectangle",
    "RowGroup",
    "RowGroupingMapper",
    "RowGroupingMapperResult",
    "RowGroupingOptions",
    "RowIDCell",
    "SelectionBlending",
    "SelectionRange",
    "SizedGridColumn",
    "Slice",
    "Sprite",
    "SpriteMap",
    "SpriteProps",
    "TextCell",
    "TextCellEntry",
    "Theme",
    "UriCell",
    "UseRowGroupingResult",
    "ValidatedGridCell",
    "blend",
    "booleanCellIsEditable",
    "booleanCellRenderer",
    "bubbleCellRenderer",
    "decodeHTML",
    "default",
    "drawTextCell",
    "drilldownCellRenderer",
    "emptyGridSelection",
    "getCopyBufferContents",
    "getDefaultTheme",
    "getEmHeight",
    "getLuminance",
    "getMiddleCenterBias",
    "imageCellRenderer",
    "interpolateColors",
    "isEditableGridCell",
    "isInnerOnlyCell",
    "isObjectEditorCallbackResult",
    "isReadWriteCell",
    "isRectangleEqual",
    "isSizedGridColumn",
    "isTextEditableGridCell",
    "loadingCellRenderer",
    "markdownCellRenderer",
    "markerCellRenderer",
    "measureTextCached",
    "newRowCellRenderer",
    "numberCellRenderer",
    "parseToRgba",
    "protectedCellRenderer",
    "resolveCellsThunk",
    "roundedPoly",
    "roundedRect",
    "rowIDCellRenderer",
    "sprites",
    "textCellRenderer",
    "uriCellRenderer",
    "useColumnSizer",
    "useRowGrouping",
    "useTheme",
    "withAlpha",
];

/**
 * AI Fill additions (SPST-16). Every name must follow {@link aiFillNamingRule},
 * so AI Fill never takes a generic name from core's namespace.
 */
const aiFillExports = [
    "AICellContext",
    "AICellStatus",
    "AIColumnDefinition",
    "AIColumnDefinitionBase",
    "AIColumnDefinitionFor",
    "AIColumnId",
    "AICommitEdit",
    "AICommitEvent",
    "AIDecideContext",
    "AIDecideResult",
    "AIDecideStatus",
    "AIDecisionReason",
    "AIFillConfig",
    "AIFillConfigIssue",
    "AIFillConnection",
    "AIFillCustomConnection",
    "AIFillDirectConnection",
    "AIFillEndpointConnection",
    "AIFillError",
    "AIFillErrorKind",
    "AIFillExecutionOptions",
    "AIFillMode",
    "AIFillRows",
    "AIFillScope",
    "AIGateName",
    "AIJsonObject",
    "AIJsonValue",
    "AIMappedOutput",
    "AIOutputBase",
    "AIOverwritePolicy",
    "AIPolicy",
    "AIPolicyDecision",
    "AIPolicyEvaluation",
    "AIPolicyStatus",
    "AIRange",
    "AIRejectEvent",
    "AIResultEvent",
    "AIResultMetadata",
    "AIRowContext",
    "AIRowId",
    "AIRowScope",
    "AIRunProgressEvent",
    "AIRunStartEvent",
    "AIRunSummary",
    "AISemanticOutcome",
    "AISkipReason",
    "ChoiceAnswer",
    "ChoiceColumnDefinition",
    "ChoiceGate",
    "ChoiceOption",
    "ChoicePolicy",
    "ChoicePresentation",
    "EvaluateAIPolicyInput",
    "JevAnswer",
    "JevAnswerFor",
    "JevChoiceAnswer",
    "JevChoiceQuestion",
    "JevInstructions",
    "JevNoulAnswer",
    "JevNoulQuestion",
    "JevPrimitive",
    "JevQuestion",
    "JevRequest",
    "JevResponse",
    "JevScoreAnswer",
    "JevScoreQuestion",
    "JevState",
    "MapAIOutputError",
    "MapAIOutputResult",
    "NoulAnswer",
    "NoulBands",
    "NoulColumnDefinition",
    "NoulGate",
    "NoulLabels",
    "NoulOutput",
    "NoulPolicy",
    "NoulPresentation",
    "ParseJevAnswerResult",
    "ParsedJevAnswer",
    "ScoreAnswer",
    "ScoreColumnDefinition",
    "ScoreGate",
    "ScoreLevel",
    "ScoreOutput",
    "ScorePolicy",
    "ScorePresentation",
    "ValidateAIFillConfigOptions",
    "evaluateAIPolicy",
    "isAIDestinationEmpty",
    "mapAIOutput",
    "parseJevAnswer",
    "validateAIFillConfig",
];

/** Contains `AI`, `AIFill` or `Jev`, or starts with `Choice`, `Score` or `Noul`. */
const aiFillNamingRule = /AI|Jev|^(?:Choice|Score|Noul)/;

const expectedExports = [...upstreamExports, ...aiFillExports].sort();

function getExportedNames(entry: string): string[] {
    const program = ts.createProgram([entry], {
        allowJs: true,
        skipLibCheck: true,
        noEmit: true,
        module: ts.ModuleKind.ESNext,
        target: ts.ScriptTarget.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
    });
    const checker = program.getTypeChecker();
    const sourceFile = program.getSourceFile(entry);
    if (sourceFile === undefined) throw new Error(`Could not load ${entry}`);
    const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
    if (moduleSymbol === undefined) throw new Error(`No module symbol for ${entry}`);
    return checker
        .getExportsOfModule(moduleSymbol)
        .map(symbol => symbol.name)
        .sort();
}

describe("public API exports", () => {
    it("match the 6.0.4-alpha25 export list plus the AI Fill additions", () => {
        const entry = path.resolve("src/index.ts");
        expect(getExportedNames(entry)).toEqual(expectedExports);
    });

    it("keep every 6.0.4-alpha25 name and add only names that follow the AI Fill naming rule", () => {
        expect(upstreamExports).toHaveLength(151);
        const added = expectedExports.filter(name => !upstreamExports.includes(name));
        expect(added).toEqual(aiFillExports);
        expect(added.filter(name => !aiFillNamingRule.test(name))).toEqual([]);
    });
});
